

#================================================================
#   Copyright (C) 2024 Goldman Ltd. All rights reserved.
#   
#   File：Makefile
#   Author：leekaihua
#   Date：2024年05月17日
#   Brife：
#
#================================================================

OBJS = add.o sub.o mul.o div.o test.o

test: ${OBJS}
	gcc ${OBJS} -o test

add.o: add.c
	gcc -c add.c -o add.o
sub.o: sub.c
	gcc -c sub.c -o sub.o
mul.o: mul.c
	gcc -c mul.c -o mul.o
div.o: div.c
	gcc -c div.c -o div.o

clean:
	rm -rf ${OBJS} test
