

#================================================================
#   Copyright (C) 2024 Goldman Ltd. All rights reserved.
#   
#   File：Makefile
#   Author：leekaihua
#   Date：2024年04月27日
#   Brife：
#
#================================================================


all : request.cpp factory.cpp historical_person.cpp star_person.cpp
	g++ request.cpp factory.cpp historical_person.cpp star_person.cpp -std=c++11 -Wall -g -o request